before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y groff

script:
    - make -C protocols/ all html
    - cp theme/index.html .
    - mkdir build && cp -v protocols/*.{html,txt,term} build/.

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch:
            - master
